source 'https://git.hzdlsoft.com/ios_lib/DLPods.git'
source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
platform :ios, '9.0'

target 'DLShareModuleIOSExample' do
#private
  pod 'React', :path => '../node_modules/react-native'
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
end
