inhibit_all_warnings!
platform :ios, '8.0'
use_frameworks!

target 'VideoBox' do
    pod 'AVOSCloud'               # 数据存储、短信、云引擎调用等基础服务模块
    pod 'AVOSCloudIM'             # 实时通信模块
    pod 'AVOSCloudCrashReporting' # 错误报告模块
    
    pod 'IQKeyboardManager'
    pod 'MJExtension'
    pod 'MJRefresh'
    pod 'Colours'
    pod 'ReactiveCocoa', '~> 2.5'

    pod 'pop'
# 'node_modules'目录一般位于根目录中
# 但是如果你的结构不同，那你就要根据实际路径修改下面的`:path`
pod 'React', :path => '../node_modules/react-native', :subspecs => [
'Core',
'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
'RCTText',
'RCTNetwork',
'RCTWebSocket', # 这个模块是用于调试功能的
# 在这里继续添加你所需要的模块
]
# 如果你的RN版本 >= 0.42.0，则加入下面这行
pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

end
